-- Database export: clinic
-- Date: 2026-06-11 15:28:39
-- Generated by DBX

CREATE TABLE "public"."appointment_history" (
  "history_id" integer NOT NULL DEFAULT nextval('appointment_history_history_id_seq'::regclass),
  "appointment_id" integer,
  "old_status" text,
  "new_status" text,
  "changed_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("history_id"),
  CONSTRAINT "appointment_history_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("appointment_id")
);
;

CREATE TABLE "public"."appointments" (
  "appointment_id" integer NOT NULL DEFAULT nextval('appointments_appointment_id_seq'::regclass),
  "patient_id" integer,
  "doctor_id" integer,
  "slot_id" integer,
  "status" text,
  "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("appointment_id"),
  CONSTRAINT "appointments_doctor_id_fkey" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("doctor_id"),
  CONSTRAINT "appointments_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "patients"("patient_id"),
  CONSTRAINT "appointments_slot_id_fkey" FOREIGN KEY ("slot_id") REFERENCES "slots"("slot_id")
);
;

CREATE TABLE "public"."doctors" (
  "doctor_id" integer NOT NULL DEFAULT nextval('doctors_doctor_id_seq'::regclass),
  "first_name" text NOT NULL,
  "last_name" text,
  "specialization" text,
  "phone" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("doctor_id")
);

CREATE UNIQUE INDEX "doctors_phone_key" ON "public"."doctors" USING btree ("phone");;

CREATE TABLE "public"."patients" (
  "patient_id" integer NOT NULL DEFAULT nextval('patients_patient_id_seq'::regclass),
  "first_name" text NOT NULL,
  "last_name" text,
  "gender" text,
  "dob" date,
  "phone" text NOT NULL,
  "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("patient_id")
);

CREATE UNIQUE INDEX "patients_phone_key" ON "public"."patients" USING btree ("phone");;

CREATE TABLE "public"."slots" (
  "slot_id" integer NOT NULL DEFAULT nextval('slots_slot_id_seq'::regclass),
  "doctor_id" integer,
  "slot_time" timestamp without time zone NOT NULL,
  "status" text DEFAULT 'available'::text,
  PRIMARY KEY ("slot_id"),
  CONSTRAINT "slots_doctor_id_fkey" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("doctor_id")
);
;

CREATE TABLE "public"."staff" (
  "staff_id" integer NOT NULL DEFAULT nextval('staff_staff_id_seq'::regclass),
  "staff_name" text NOT NULL,
  "phone" text NOT NULL,
  PRIMARY KEY ("staff_id")
);
;

